### ISSUE TITLE
Rectify big gaps between rows on homepage tiling 

### ISSUE THREAD

**Issue by andrejvidic** [RHoKAustralia/melb-social-catalysts#1]

**Comment by yakovkhalinsky** [comment]
Due to variable heights on the tiles, this means that if a tile is shorted than others, a single tile will show up on a row (on it's own) and the rest will break to another line.

Investigating better ways to deal with this.

**Comment by yakovkhalinsky** [comment]
@socialcatalysts1 @EvilAngelPixie done a bit of work on scripting the resizing of the heights of the tiles.
Should be reasonably stable, ready for QA :+1:

**Comment by EvilAngelPixie** [comment]
@yakovkhalinsky looking good! Have tested it on smallish, normal and crazy resolutions and it scales really well :clap:

**Comment by socialcatalysts1** [comment]
It looks great! Feel free to "close" the issue. :)
