### ISSUE TITLE
Back to top button obscures tags menu on small screen size

### ISSUE THREAD

**Issue by yakovkhalinsky** [RHoKAustralia/melb-social-catalysts#10]
When you reduce the width to small screen size (top menu fully collapsed), the `back to top` button sits over the top of the tags list.

**Comment by EvilAngelPixie** [comment]
(iPhone 6) No longer obscuring, but the tag list seems to be reacting a bit weirdly to it. 
![img_3898](https://cloud.githubusercontent.com/assets/3608343/7925929/4254ac82-090e-11e5-87bb-f75985333124.PNG)

**Comment by EvilAngelPixie** [comment]
Would replacing the RSS button with back to top help keep it out of the way?

**Comment by socialcatalysts1** [comment]
It's looking alright, I think there are too many tags on the bottom of the page which kind of detracts from the "back to top button".. I think perhaps moving the button up closer to the top will make it more easily visible.

**Comment by yakovkhalinsky** [comment]
Yep, will need to fix the way the tags are laying out, not sure why there are line breaks (will fix).

And will make sure the 'top' button is at the top of the footer.

**Comment by yakovkhalinsky** [comment]
@EvilAngelPixie the RSS button is positioned over the top, but I'm planning on killing it altogether.

@socialcatalysts1 if you're ok with that? I'm pretty sure your target audiences don't use RSS feeds :)

**Comment by socialcatalysts1** [comment]
Sure, go for it! I have no idea what RSS feeds are..

**Comment by andrejvidic** [comment]
They are a way to subscribe to a page and be notified as soon as a change or addition is made to that page

**Comment by EvilAngelPixie** [comment]
Have 'repurposed' the subscribe button and replaced it with 'back to top' - let me know what you think, the tag block is still misbehaving a bit on iPhone 6 screen (still wrapping tags as per the screenshot above) but at least the positioning of the button isn't contributing anymore.

(Also wasn't sure how persistent the base screen.css will be, so it might be worth overloading subscribe in sc.css and modifying it there?)

**Comment by yakovkhalinsky** [comment]
@EvilAngelPixie yep I definitely like that much better, and being white it stands out a bit more over the footer background.

What do you guys thing? @socialcatalysts1

**Comment by socialcatalysts1** [comment]
Thanks for that @EvilAngelPixie, I like the positioning of the back to the top button.

**Comment by yakovkhalinsky** [comment]
@socialcatalysts1 are you guys ok if we close this issue?

**Comment by EvilAngelPixie** [comment]
Tags look awesome @yakovkhalinsky !

**Comment by sawilde** [comment]
:+1:

**Comment by socialcatalysts1** [comment]
@yakovkhalinsky Feel free to close this. :)
