### ISSUE TITLE
older posts button positioning

### ISSUE THREAD

**Issue by yakovkhalinsky** [RHoKAustralia/melb-social-catalysts#11]
![image](https://cloud.githubusercontent.com/assets/646086/7923462/9c68ee80-08f6-11e5-8846-80d8a851e77e.png)

**Comment by socialcatalysts1** [comment]
Looks good, feel free to close. :)

**Comment by yakovkhalinsky** [comment]
I've removed the border on small screen sizes to resolve this, as well as the `newer posts` button on the archive list page. 

I'm happy to close this now :+1:
