### ISSUE TITLE
Add background pattern/texture

### ISSUE THREAD

**Issue by EvilAngelPixie** [RHoKAustralia/melb-social-catalysts#13]
Background texture for behind tile/article display

![gplaypattern](https://cloud.githubusercontent.com/assets/3608343/7934140/29f324e8-0968-11e5-9cd5-1b9dc861710a.png)

**Comment by sawilde** [comment]
sweet :)

**Comment by EvilAngelPixie** [comment]
Ready for QA

**Comment by yakovkhalinsky** [comment]
Awesome! Looks great.

I'm happy to sign off on this if you guys are ok with it :+1:

**Comment by EvilAngelPixie** [comment]
@socialcatalysts1 are you happy with the background? If you are, I'll close the issue.

**Comment by socialcatalysts1** [comment]
The background texture looks good, thanks Samara! :)

**Comment by EvilAngelPixie** [comment]
@socialcatalysts1 no worries - I'll close off the issue (another one down!)
