### ISSUE TITLE
Page 2 article tiles have lost their images

### ISSUE THREAD

**Issue by EvilAngelPixie** [RHoKAustralia/melb-social-catalysts#15]
This seems to be a bug we've introduced since the hackathon weekend - article content/settings are still the same, but articles on page 2 no longer display images on the tiles.

Have tried deleting and restoring images and a couple of other things in the CMS, but no joy.

**Comment by yakovkhalinsky** [comment]
Ok guys this should be fixed now.

Was due to a missing CSS rule.

Pinging @socialcatalysts1

**Comment by yakovkhalinsky** [comment]
Looks like this is resolved, closing
