### ISSUE TITLE
Migrate remainder of static pages

### ISSUE THREAD

**Issue by EvilAngelPixie** [RHoKAustralia/melb-social-catalysts#16]
There are static pages that still need to be moved over.

**Comment by EvilAngelPixie** [comment]
'Who We Are' and 'Get Involved' are up - do we have a preferred solution for the email form. The Ghost preferred solution seems to be https://odamae.io.

Thoughts?

**Comment by yakovkhalinsky** [comment]
hmm we could do a simple microservice that takes form submissions, wouldn't be hard, we need to work out exactly what they guys need to get for submissions, or is an email address sufficient?

**Comment by socialcatalysts1** [comment]
Thanks Samara, just signed up on odamae.io and got the code off there. Form all done!

**Comment by socialcatalysts1** [comment]
Hi @EvilAngelPixie , just wondering can you please "close" this, all relevant content has been transferred over. Thanks!

**Comment by EvilAngelPixie** [comment]
Done :)
