### ISSUE TITLE
Home button "SC" to access homepage on Iphones

### ISSUE THREAD

**Issue by socialcatalysts1** [RHoKAustralia/melb-social-catalysts#6]

**Comment by yakovkhalinsky** [comment]
Certain widths also throw the menu onto the next line, will fix this at the same :8ball:

**Comment by yakovkhalinsky** [comment]
I've added the SC to both the header (at small screen sizes) as well as to the footer (always visible).

I'll leave this open for some QA.

**Comment by EvilAngelPixie** [comment]
(iPhone6) looks like the YouTube button has been pushed off the header and is ghosting underneath... 
![img_3897](https://cloud.githubusercontent.com/assets/3608343/7925853/383cd5c2-090d-11e5-9d71-e7657e7eb5c2.PNG)

**Comment by EvilAngelPixie** [comment]
Do you think the SC needs to be bold or something similar to differentiate it from About and Submit Article?

**Comment by yakovkhalinsky** [comment]
I'll make the SC a bit heavier, I also thought about putting a white circle around it, I'll try out both these and post screen shots.

In regards to the youtube link, I think I need to stick a min-width around all of this part of the menu to make sure it doesn't get kicked to another line.

**Comment by socialcatalysts1** [comment]
Thanks for working on this Yakov, yep I can now access the home page via the SC button. Sure, feel free to put a circle/some sort of shape around it for greater emphasis.

**Comment by yakovkhalinsky** [comment]
@socialcatalysts1 are you guys ok with closing this issue?

**Comment by socialcatalysts1** [comment]
Sure, go for it! :)
