### ISSUE TITLE
"Take Action" button under each article 

### ISSUE THREAD

**Issue by socialcatalysts1** [RHoKAustralia/melb-social-catalysts#8]

**Comment by andrejvidic** [comment]
My thoughts are firstly create a hidden section that opens on click to reveal the take action text/links etc.

Doing this will mean that updating pages using the web login will become a little more complicated. 

For starters I will look at getting the above working and document how to use it. 

As a long term solution I aim to look at the possibility of modifying the Ghost GUI interface to see if it is possible to add a third markdown input box (Title is one, Content is the second). This will mean that any code will be removed from the web login edit boxes.

**Comment by socialcatalysts1** [comment]
@yakovkhalinsky This has been kinda addressed already.:)
