### ISSUE TITLE
Hook up tags generations script to scheduled job

### ISSUE THREAD

**Issue by yakovkhalinsky** [RHoKAustralia/melb-social-catalysts#9]
`node tags.js` needs to regularly run, probably as a cron job on the server to generate the `tags.json` file that we currently use to populate the tag menu in the footer.

**Comment by yakovkhalinsky** [comment]
It currently runs when the `redeploy.sh` script is executed.

Will need to have this up and running before we switch the site over to ghost.

**Comment by EvilAngelPixie** [comment]
Have had two successfully run cronjobs refreshing the tags, so calling this one closed!
